- env/prow/values.tmpl.yaml
Incorporates https://github.com/jenkins-x/test-infra/pull/18
> fix: fix pipeline reconcilation

- env/prow/values.tmpl.yaml
Reverts jenkins-x/environment-tekton-weasel-dev#41
> revert: enable meta pipeline

- env/templates/e2e-gc-cj.yaml
> fix: Add GKE GC cronjob

- env/jenkins-x-platform/values.tmpl.yaml
> fix: Update gcactivities to not delete all the things

- env/jenkins-x-platform/values.tmpl.yaml
- env/values.tmpl.yaml
> fix: chartmuseum config should be in jenkins-x-platform/values.tmpl.yaml

- OWNERS
- env/templates/version-stream-update-cj.yaml
Also added myself to `OWNERS`.
> fix: Needed a newer image for version stream update cronjob

- env/templates/version-stream-update-cj.yaml
> fix: Another attempt to fix the version stream update cronjob

- env/templates/version-stream-update-cj.yaml
> fix: Get rid of dangling dash

- env/templates/version-stream-update-cj.yaml
> fix: Set PIPELINE_KIND to pick up creds for version stream update

- env/jenkins-x-platform/values.tmpl.yaml
> fix: Bump the chartmuseum resource requests and limits

- env/prow/values.tmpl.yaml
> fix: Reenable metapipeline, bump prow pipeline image

- env/templates/700-hook-ing.yaml
- env/templates/boot-config-scheduler.yaml
- env/templates/default-scheduler.yaml
- env/templates/env-scheduler.yaml
- env/templates/jx-scheduler.yaml
- env/templates/jx-versions-scheduler.yaml
See the https://github.com/jenkins-x/jx-docs/pull/1850 for more detials.
> feat: add needs-security-review label to all schedulers

- env/templates/jx-scheduler.yaml
> fix: Fix images context regexp

- env/templates/default-scheduler.yaml
> fix: report_template had wrong index in pulls

- env/templates/ci-scheduler.yaml
> fix: Fix reportTemplate in ci-scheduler.yaml as well

- env/templates/version-stream-update-cj.yaml
> chore: Exclude Lighthouse until it gets fixed. =)

- env/templates/version-stream-update-cj.yaml
now the latest lighthouse is working again
> fix: enable lighthouse PRs again

- env/prow/values.tmpl.yaml
> fix: Turn on metapipeline again

- env/prow/values.tmpl.yaml
> fix: Switch to metapipeline again

- env/templates/version-stream-update-cj.yaml
Picks up fixes to `jx step create pr`
> fix: Bump version update cronjob builder image

- env/templates/boot-config-scheduler.yaml
- env/templates/jx-versions-scheduler.yaml
part of https://github.com/jenkins-x/jx/issues/5868
> fix: move the bdd tests for vault with tls into versions repository

- repositories/templates/jenkins-x.yaml
part of https://github.com/jenkins-x/jx-release-version/issues/40
> feat: import the jx-release-version project

- env/prow/values.tmpl.yaml
> chore: Disable prow-build since we don't need it

- env/templates/lh-scheduler.yaml
- repositories/templates/lh-group.yaml
> chore: Add new Lighthouse contexts for BDD tests

- env/jenkins-x-platform/values.tmpl.yaml
> fix: Stop doing git credentials stuff in build controller

- env/jenkins-x-platform/values.tmpl.yaml
> fix: Fixing env specification for build controller

- env/templates/jx-scheduler.yaml
> fix: adding a unit context to scheduler configuration

- env/templates/lighthouse-test-secret.yaml
- env/templates/versions-test-secret.yaml
- env/values.tmpl.yaml
> chore: Add versions and LH bot test users

- env/templates/lh-scheduler.yaml
> fix: Make gitlab context for Lighthouse required

- env/templates/jx-versions-scheduler.yaml
Enables the boot upgrade bdd test to auto run
> chore: Enable upgrade test

- env/templates/jx-scheduler.yaml
> chore: Add optional boot-lh-ghe context to jx.

- env/templates/jx-scheduler.yaml
> fix: Whoops, boot-lh-ghe should not always run on jx

- repositories/templates/jenkins-x.yaml
> chore: Add jx-convert-jenkinsfile repo

- env/templates/lh-scheduler.yaml
The server's actually working again, so. =)
> chore: Turn BitBucket Server back on for Lighthouse tests

- env/templates/arcalos-prod-secret.yaml
- env/values.tmpl.yaml
> chore: added arcalos-prod-secret

- repositories/templates/cloudbees.yaml
> fix: Rename tekton-sdm-app SR to match standard format

- env/templates/jx-scheduler.yaml
depends on https://github.com/jenkins-x/jx/pull/6638
> chore: making unit context always run

- repositories/templates/cloudbees.yaml
> chore: adds source repo arcalos-instance-template

- env/templates/lh-scheduler.yaml
Prep for https://github.com/jenkins-x/jx/issues/6651
> chore: Add new migrate-from-prow optional context to Lighthouse

- jenkins-x.yml
> fix: Update the release pipeline too

- env/templates/arcalos-version-stream-update-cj.yaml
Reverts jenkins-x/environment-tekton-weasel-dev#343
> chore: revert - removed exclusion on jx-repository-controller

- env/requirements.yaml
This fixes an type assertion error
> chore: move to jx-sdm-app 0.0.8

- env/jx-sdm-app/values.tmpl.yaml
- env/requirements.yaml
Also configure a higher memory limit
> chore(deps): bump jx-sdm-app to 0.0.9

- repositories/templates/jenkins-x-apps.yaml
https://github.com/jenkins-x-apps/jx-app-fossa - added as part of https://github.com/jenkins-x/jx/issues/6567
> chore: Add jx-app-fossa repo

- env/templates/arcalos-config-configmap.yaml
> feat: add arcalos configuration configmap

- repositories/templates/cloudbees.yaml
> chore: adds source repo arcalos-config

- jx-requirements.yml
fixes https://github.com/jenkins-x/jx/issues/6650
> chore: Switch to Lighthouse rather than Prow

- env/jenkins-x-platform/values.tmpl.yaml
- jx-requirements.yml
> chore: Revert to Prow due to PRs not getting log links

- env/templates/copy-charts-index-cj.yaml
> chore: Turn off caching completely for chartmuseum index.yaml

- jx-requirements.yml
Take this off hold if any crippling issues with Lighthouse show up, but please comment with what problems you're seeing before you do so.
> chore: Revert to Prow

- jx-requirements.yml
Specifically https://github.com/jenkins-x/lighthouse/issues/540 and https://github.com/jenkins-x/lighthouse/issues/542
> chore: Switch to LH after latest fixes

- jx-requirements.yml
> chore: Revert to Prow from LH dogfooding

- env/requirements.yaml
- jx-requirements.yml
> chore: Revert to Prow, Feb 28

- repositories/templates/cloudbees.yaml
> chore: add arcalos-setup repository

- env/templates/arcalos-alpha-prod-secret.yaml
> feat: added the arcalos-alpha-prod-secret

- env/templates/arcalos-version-stream-update-cj.yaml
- env/templates/jx-versions-scheduler.yaml
- env/templates/version-stream-update-cj.yaml
by default to ensure they keep working
> fix: enable the helm 3 single + multi cluster BDD tests

- env/templates/arcalos-version-stream-update-cj.yaml
> fix: re-enable jx-repository-controller in version stream pr

- env/templates/arcalos-version-stream-update-cj.yaml
Reverts jenkins-x/environment-tekton-weasel-dev#433
> fix: Revert - re-enable jx-repository-controller in version stream pr

- repositories/templates/jenkins-x.yaml
Adding the new EKS terraform repo.
> feat: add the eks terraform repo to the cluster

- env/templates/jx-versions-scheduler.yaml
> fix: Don't run the helm3 and helm3-mc version stream tests automatically

- env/templates/aws-creds-secret.yaml
- env/values.tmpl.yaml
Adding AWS creds for the Terraform script tests
> feat: create aws creds secret and add them to the values file

- env/templates/arcalos-version-stream-update-cj.yaml
> fix: another attempt to include jx-repository-controller

- env/templates/arcalos-version-stream-update-cj.yaml
Reverts jenkins-x/environment-tekton-weasel-dev#435
> revert: "fix: another attempt to include jx-repository-controller"

- repositories/templates/jenkins-x.yaml
> chore: add jx-logging SourceRepository

- env/jx-app-athens/templates/app.yaml
- env/requirements.yaml
> chore: Upgrade Athens again

- env/lighthouse/values.tmpl.yaml
- env/templates/jx-scheduler.yaml
- env/templates/jx-versions-scheduler.yaml
- jx-requirements.yml
> chore: Switch to Lighthouse yet again

- env/requirements.yaml
> fix: Don't pin lighthouse version

- repositories/templates/jenkins-x.yaml
I think this may have confused Lighthouse a bit.
> chore: Remove archived repos

- env/requirements.yaml
This version has some critical fixes. I'll remove this once it's in the version stream.
> chore: Use a hardcoded Lighthouse version briefly

- env/requirements.yaml
> chore: Update to Lighthouse 0.0.546

- env/requirements.yaml
> chore: Switch back to version stream version of Lighthouse

- env/templates/git-test-gitlab-approver-secret.yaml
- env/values.tmpl.yaml
> chore: Add GitLab approver user secret

- env/prow/values.tmpl.yaml
- env/requirements.yaml
> fix: Somehow Prow came back. Let's not let that happen again.

- env/templates/git-test-bbs-approver-secret.yaml
- env/values.tmpl.yaml
> chore: Add BBS approver user secret

- repositories/templates/jenkins-x-apps.yaml
Adds the sonar app to be built on the weasel cluster
> chore: Add sonar app

- env/requirements.yaml
> fix: Revert to UI 0.0.1270 for the moment

- env/requirements.yaml
> chore: try an earlier UI version

- env/requirements.yaml
- env/ui/values.tmpl.yaml
rolls back the sso fix attempts:
* #615
* #616
> fix: rollback sso fix attempts

- env/requirements.yaml
- env/ui/values.tmpl.yaml
This is the follow-up PR of #615 and #616
Depends on https://github.com/cloudbees/jxui-frontend/pull/1527/
> fix: jxui sso config

- jx-requirements.yml
> fix: Use the sha for the correct version stream tag, not the wrong one I did initially

- repositories/templates/jenkins-x-apps.yaml
Importing the kubeless app in to the source repositories
> chore: Import the kubeless app

- repositories/templates/jenkins-x.yaml
- repositories/templates/lh-group.yaml
> chore: Actually remove Lighthouse

- repositories/templates/default-group.yaml
> fix: whoops needed default-group.yaml
