jenkins-x/environment-tekton-weasel-dev

env/jenkins-x-platform/values.tmpl.yaml
Previously they were running at 0 and 30 past the hour every third
hour, which was...odd.
=> chore: Run gc pods and gc activities every half hour

env/templates/version-stream-update-cj.yaml
Not 100% this is right, but I think it is?
=> fix: jx-version-stream-update cronjob needs git info and creds

env/templates/version-stream-update-cj.yaml
* wasn't updating the builders so added `--images
* exclude `cert-manager` as they made breaking changes
=> fix: add the builders, remove cert-manager

env/prow/values.tmpl.yaml
See https://github.com/jenkins-x/jx/issues/5208
=> fix: Re-disable metapipeline due to json logging breaking tests

env/templates/version-stream-update-cj.yaml
This picks up the various changes in https://github.com/jenkins-x/jx/pull/5227
=> fix: Bump version stream cronjob image to 0.1.672

env/templates/version-stream-update-cj.yaml
This will get the cronjob actually functioning again.
=> fix: remove quotes from version stream cronjob args, bump image

env/templates/e2e-gc-cj.yaml
This'll keep it from deleting `boot-lh` clusters when there's a
`boot-lh-ghe` running, due to (until now) it checking whether another
running cluster _contains_ the first cluster's type.
=> fix: Pick up latest image for e2e gc cronjob

env/templates/version-stream-update-cj.yaml
This picks up a couple fixes to `jx step create pr versions`.
=> fix: Bump version stream cronjob image

env/jenkins-x-platform/values.tmpl.yaml
This'll pick up the fix for the parameters being flipped for release
age and PR age, so that we actually delete PRs after two days and keep
releases for 30.
=> fix: Update gc activities cronjob image

env/prow/values.tmpl.yaml, env/templates/gh-test-secret.yaml, env/templates/git-test-bbs-secret.yaml, env/templates/git-test-ghe-secret.yaml, env/templates/git-test-gitlab-secret.yaml
so we don't load these secrets into the git auth, breaking build controller and possibly other things
=> fix: remove git labels from test secrets

env/jenkins-x-platform/values.tmpl.yaml, env/prow/values.tmpl.yaml
This will get `PipelineRun`s properly GCed now that they're
disconnected from `PipelineActivity`s, and sync the `pipeline` prow
image with the rest of Prow, now that there's a Prow release with the
relevant fixes from Pete's image in it. That'll also pick up the
theoretical fix for the `pipeline not found` error, though I can't be
100% sure that'll work correctly, so I'll be monitoring things...intensely.
=> fix: Update gcactivities image and prow pipeline image

env/prow/values.tmpl.yaml
This'll end up in the version stream tonight, but the current state of
the auto-retry on `pipeline not found` is...not good, so let's bump
the image for the moment.
=> fix: Use newer pipeline image from prow for the moment

env/prow/values.tmpl.yaml
There's an issue with the prow build link ending up always pointing to
build 1.
=> fix: Turn metapipeline back off

env/jenkins-x-platform/values.tmpl.yaml, env/prow/values.tmpl.yaml, env/templates/copy-charts-index-cj.yaml, env/templates/e2e-gc-cj.yaml, env/templates/version-stream-update-cj.yaml
There's no need to use custom tags on these any more. This doesn't turn on metapipeline or anything, mind you.
Also updated cronjob images to use the most recent. I left the `jenkins-x.yml` tags as they are because, well, didn't see a need to change them. =)
Holding until https://github.com/jenkins-x/jenkins-x-versions/pull/493 is merged
/hold
=> fix: Switch a few images to use version stream instead of explicit

env/templates/ci-scheduler.yaml
We only want the `ci` context for the frontend.
=> feat: add replace:true to presubmits to avoid having the default scheduler context for ci builds

env/templates/jx-scheduler.yaml
For the moment, this isn't going to be run by default and isn't a
required context, until we have it working correctly on https://github.com/jenkins-x/jx/pull/5607
=> chore: Add boot-vault context to jx

repositories/templates/cloudbees.yaml
=> fix: Use consistent source repo name for jenkins-x-github-app

env/templates/jx-versions-scheduler.yaml
Removes `ng` and `gitops` from required, since they're awfully legacy codepaths, and removes `ng`, `gitops`, `boot-jenkins`, and `tiller` from `/test all` because...well, why not.
=> fix: Clean up jenkins-x-versions contexts

env/templates/jx-scheduler.yaml
Holding until https://github.com/jenkins-x/jx/pull/5607 (or more likely a PR from @rawlingsj) has merged.
=> chore: Make boot-vault context required on jx PRs

env/jenkins-x-platform/values.tmpl.yaml
Will remove this once https://github.com/jenkins-x/jx/pull/5651 is
merged/released/in version stream, but this unbreaks `controllerbuild`
LTS log archiving for the moment.
=> fix: Use temporary image for controllerbuild

env/jenkins-x-platform/values.tmpl.yaml
This reverts commit 7a370f0a34a5b9e51566d13934a6f0980d0e2eff.
No longer needed - it's in the version stream now.
/assign @ccojocar
=> fix: Stop using PR-5651 image for controllerbuild

env/jenkins-x-platform/values.tmpl.yaml
Needed until https://github.com/jenkins-x/jx/issues/5665 is fixed.
=> fix: Remove configmaps from controllerbuild role

env/templates/e2e-gc-cj.yaml
This'll make it clean up SAs with the `-dn` suffix.
=> fix: Bump e2e image

env/templates/arcalos-version-stream-update-cj.yaml
To match that used by the OSS version stream update cronjob
=> fix: Bump arcalos version update cronjob builder image

env/templates/bdd-jx-scheduler.yaml, repositories/templates/bdd-jx-group.yaml, repositories/templates/jenkins-x.yaml
I'm not sure how to get Prow to merge PRs without calling post-submits
afterwards, so for the moment, I decided to just copy what
`jenkins-x-boot-config` does and use a different context than the
default so we can have a no-op release in `bdd-jx/jenkins-x-release.yml`.
This will want to be merged before I add that to `bdd-jx`.
=> chore: Run bdd-jx postsubmits from `jenkins-x-release.yml`.

repositories/templates/cloudbees.yaml
Since we shouldn't be building it here.
=> fix: Remove cloudbees-jenkins-x-distro repo

env/templates/lh-scheduler.yaml
The tests are actually working now, so let's make these contexts required.
=> chore: Make github and ghe contexts for lighthouse required

OWNERS, env/jx-app-ui/values.tmpl.yaml
=> chore: Set a higher memory limit for jxui than the default

env/jenkins-x-platform/values.tmpl.yaml
At least until we nail down
https://github.com/jenkins-x/jx/issues/6217 and https://github.com/jenkins-x/jx/issues/6246.
=> chore: Turning on debug logging in build controller

env/templates/000-namespace.yaml
It never should have worked, and with kubectl 1.17, it errors rather than silently discarding invalid metadata values like this one.
=> fix: quote boolean label value in namespace template

repositories/templates/jenkins-x.yaml
=> fix: Proper naming of hugo-extended-docker

env/templates/lh-scheduler.yaml
"bitbucketserver" was excessively long. =)
=> fix: Rename Lighthouse's Bitbucket Server context to bbs

env/templates/lh-scheduler.yaml
Our BitBucket Server instance is working again, so let's make this mandatory
=> chore: Require BitBucket context on Lighthouse

env/templates/version-stream-update-cj.yaml
With `stable/nginx-ingress` 1.29.0 or 1.29.1 (the latest release as of
this time), ingresses aren't getting addresses. While this issue is
being investigated, we should stick with 1.28.3 for `stable/nginx-ingress`.
=> chore: Stop updating stable/nginx-ingress in version stream update cronjob

env/templates/boot-config-scheduler.yaml
=> fix: Make jenkins-x-boot-config use rebase for PR merges

env/templates/lh-scheduler.yaml
Looks like our license isn't valid or something, so...yeah. Let's
disable again.
=> chore: Disable BBS context on Lighthouse due to BBS test instance issues

env/templates/lh-scheduler.yaml
Specifically `/test bdd` for all the BDD contexts, and `/test all-gh`
for both `github` and `ghe`. Just to save me making multiple `/test`
comments when I'm trying to rerun some but not all tests. =)
=> chore: Convenience /test commands for Lighthouse repo

env/lighthouse/values.tmpl.yaml, jenkins-x.yml
Part of preparing to switch tekton-weasel to use Lighthouse as its webhook engine.
Note that this isn't actually changing anything in the cluster, just making sure that when we do switch to Lighthouse, all we need to do is change `jx-requirements.yaml`'s `webhook` value.
Normally anyone switching from Prow to Lighthouse from an older boot config would need to do `jx upgrade boot` first to pick this up, but I wanna touch as little as possible here. =)
=> chore: Update lighthouse values.tmpl.yaml from upstream

env/lighthouse/values.tmpl.yaml, env/requirements.yaml
Yeah, I dunno why the original didn't work with the jx in builder
0.1.658, leading to that whole rabbit hole stemming from updating the
builder, but I believe this one will work without needing to change
the builder.
=> chore: Update lighthouse values that'll work with ancient builder

env/requirements.yaml
This includes support for linking PRs to builds
=> chore: upgrade jx-sdm-app to 0.0.7

OWNERS, env/jenkins-x-platform/values.tmpl.yaml
It's too easy to lose track of older builds when we are removing all
PR `PipelineActivity`s after 48 hours. So let's bump that to 120 - if
there are performance problems due to the increase in CRDs retained (I
don't think there will be, but...), I'll improve `jx gc activity` to
be able to say "delete the `Pipeline` and friends after X duration,
but keep the `PipelineActivity` for Y duration".
Also add Hardy to OWNERS.
=> chore: Keep PR builds for at least 5 days.

env/templates/version-stream-update-cj.yaml
Version 1.31.0 of the nginx-ingress chart fixes it on k8s < 1.14, so
once https://github.com/jenkins-x/jenkins-x-versions/pull/826 passes,
we should re-enable automatically upgrading it again.
=> fix: Re-enable automatic updating of nginx-ingress chart for version stream

env/templates/lh-scheduler.yaml
For any number of reasons. So let's disable the context for now.
=> fix: BitBucket does not actually work well enough to be a blocker for LH

env/templates/copy-charts-index-cj.yaml
=> chore: Use gsutil and set cache control when copying charts

env/jenkins-x-platform/values.tmpl.yaml, jx-requirements.yml
With https://github.com/jenkins-x/jx/issues/6791, https://github.com/jenkins-x/jx/issues/6792, https://github.com/jenkins-x/jx/issues/6794, and https://github.com/jenkins-x/jx/issues/6796 fixed since yesterday's attempt at switching weasel to Lighthouse, it's time for another attempt.
As with the previous attempt, the assumption is that issues will be found and we'll want to roll back to Prow. Which is fine!
This does differ from the previous attempt in that I've added the new `--job-url-base=...` argument to the build controller.
=> chore: Switch to Lighthouse post-log link and retest fixes

jx-requirements.yml
We've got an old version stream here for some reason, and it's
resulting in stale images being used in the build controller and
lighthouse pods, meaning we don't actually pick up the fixes. So for
now, I'm going to just revert.
=> chore: Revert back to Prow again

env/requirements.yaml, jx-requirements.yml
I screwed up in https://github.com/jenkins-x/environment-tekton-weasel-dev/commit/57710fabed684a3897e568e6c063dd5e1112dc90 and commited something I shouldn't have. This will fix the reasons I reverted back to Prow just now.
=> chore: Fix my mixup in requirements.yaml, turn on Lighthouse again

env/lighthouse/values.tmpl.yaml
Should have been 2 - that's what it is upstream, but yeah, stale boot config etc.
=> chore: Bump Lighthouse replicaCount

env/templates/arcalos-config-configmap.yaml
The alpha environment will now use alpha for PRs
=> chore: switch arcalos to use alpha environment

env/requirements.yaml, jx-requirements.yml
The version stream update barfed due to two PRs running `boot-vault-tls` in the same 30 minute window, but since everything else passed and the failure was entirely due to hostname collisions, I'm hardcoding in the `jenkins-x-platform` and `lighthouse` versions. The revert to Prow PR will remove those.
=> chore: Dogfood Lighthouse again, Feb 28

env/templates/jx-scheduler.yaml, env/templates/whitesource-secret.yaml, env/values.tmpl.yaml
Also add a secret which holds the whitesource agent credentials.
This will run the `jenkins-x-whitesrouce.yml` pipeline from jx repository
when a pull request is merged to master. This pipeline will scan all Go
dependencies and update them to whitesource service. See for more details: https://github.com/jenkins-x/jx/pull/6849
=> feat: add a whitesource postsubmit job to jx repository

env/templates/lh-scheduler.yaml, env/templates/whitesource-scheduler.yaml, repositories/templates/whitesource-group.yaml
Created a dedicated scheduler and a source repository group for sso-operator, bucketrepo
instead of modifying the default scheduler. This would have required to add the whitesource
pipeline file to all repositories that reference the default scheduler. Otherwise the meta-pipeline
creates a default pipeline which collides with the release pipeline from jenkins-x.yml file.
See the issue https://github.com/jenkins-x/jx/issues/6864 for more details.
=> feat: enable the whitesource postsubmit job for lighthouse, bucketrepo, sso-operator

repositories/templates/whitesource-group.yaml
Add the following repositories: jx-tenant-service, lighthouse-githubapp,
jx-repository-controller, jx-arcalos-role-controller and jx-segment-controller
=> feat: add more repositories to whitesource source repository group

env/templates/git-test-ghe-approver-secret.yaml, env/values.tmpl.yaml
This is for use in Lighthouse BDD tests. The secret has been created in vault.
=> chore: Add GHE secret for an approver user

env/templates/jx-issue-lifecycle-close-cj.yaml, env/templates/jx-issue-lifecycle-rotten-cj.yaml, env/templates/jx-issue-lifecycle-stale-cj.yaml
These were run as periodics in pre-boot land - see
https://github.com/jenkins-x/prow-config-tekton/blob/master/prow/config.yaml#L2-L100. This
is my attempt to recreate them as cronjobs.
=> chore: Resurrect the lifecycle jobs

env/templates/rebase-and-lgtm-scheduler.yaml, repositories/templates/rebase-and-lgtm-group.yaml
Requires lgtm, merges via rebase, doesn't support updatebot, still just has the default context.
This initially includes jenkins-x/terraform-google-jx.
=> chore: Add rebase-and-lgtm-scheduler

env/templates/arcalos-version-stream-update-cj.yaml, env/templates/version-stream-update-cj.yaml
https://github.com/helm/charts/pull/21654 breaks upgrading deployments due to changes to the `PodDisruptionBudget` spec, which can't be changed apparently, resulting in this error in upgrades:
```
The PodDisruptionBudget "jxing-nginx-ingress-controller" is invalid: spec: Forbidden: updates to poddisruptionbudget spec are forbidden
```
So let's pin to 1.34.2 for the foreseeable future.
=> fix: Pin nginx-ingress chart to 1.34.2.

env/jx-app-athens/templates/app.yaml, env/requirements.yaml
=> chore: Bump to jx-app-athens 0.0.18 for Go 1.13 support

env/jx-app-athens/templates/app.yaml, env/requirements.yaml
Due to issues with a bad dependency failing to resolve with the newer Athens - https://github.com/jenkins-x/jx/pull/7031 fixes that but downstream builds will still fail for now, so let's be patient.
=> chore: Rollback to jx-app-athens 0.0.17

env/templates/jx-scheduler.yaml, env/templates/jx-versions-scheduler.yaml
And don't require them any more.
While we're here, remove a bunch of defunct contexts from `jenkins-x-versions` too.
=> chore: Turn off static master BDD tests by default

env/templates/jx-issue-lifecycle-close-cj.yaml, env/templates/jx-issue-lifecycle-rotten-cj.yaml, env/templates/jx-issue-lifecycle-stale-cj.yaml
This worked in Prow periodic jobs, but not in cronjobs. Fun! Here we need them all on one line. I did some experimenting and this seems to have done the trick.
=> fix: Lifecycle cronjobs don't query right with newlines in them

env/templates/jx-issue-lifecycle-close-cj.yaml, env/templates/jx-issue-lifecycle-rotten-cj.yaml, env/templates/jx-issue-lifecycle-stale-cj.yaml
They should be using the Lighthouse one now instead.
=> fix: Lifecycle cronjobs were using old Prow secret

env/templates/default-scheduler.yaml, env/templates/dev-env-scheduler.yaml, env/templates/env-scheduler.yaml, env/templates/whitesource-scheduler.yaml
None of `blunderbuss`, `heart`, or `config-updater` exist for
Lighthouse, and `config-updater` isn't actually relevant any more in
the first place, since we write to the configmaps via boot, not directly.
=> chore: Remove obsolete plugins from scheduler config

env/templates/jx-versions-scheduler.yaml
Now that we're Lighthouse by default, a Lighthouse-specific test
context doesn't make much sense.
=> chore: Get rid of boot-lh versions context

env/templates/hmacsecret.yaml, env/values.tmpl.yaml
Because we're on such an old jx version in the dev env pipeline that
it doesn't know what to do with `lighthouse-hmac-token`.
=> fix: Add legacy hmac-token secret

env/templates/e2e-gc-cj.yaml
Because otherwise it fails when executing the generated bash script
with gcloud not being on the path.
=> chore: Temporarily pinning e2e gc job to older jx image

env/templates/lh-scheduler.yaml
To be merged once we've actually merged the BBS support.
=> chore: Make BitBucket Server context required for Lighthouse PRs

env/jenkins-x-platform/values.tmpl.yaml
=> fix: Turn off gh-pages reporting in build controller

env/templates/sync-nginx-images-cj.yaml, env/templates/sync-nginx-images-script-cm.yaml
So that we don't have to depend on quay.io being up all the time,
given that it's often not.
Part of https://github.com/jenkins-x/jx/issues/7256
=> chore: Add cronjob syncing quay.io nginx ingress images to gcr.io

repositories/templates/jenkins-x.yaml
https://github.com/jenkins-x/lighthouse-config - I'm going to be switching jx and lighthouse to depend on this rather than jx depending on Prow and Lighthouse having its own copy.
This will allow us to start adding things to the config without needing a circular dependency (Lighthouse already depends on jx, so we don't want jx to depend on Lighthouse!).
=> chore: Add new lighthouse-config library repository

jx-requirements.yml
This is the last release of the version stream before https://github.com/jenkins-x/jx/releases/tag/v2.1.56, the jx release with the external vault changes that we believe are causing problems with prod builds.
We'll be building a new prod cluster/env next week so that we can actually use `jx upgrade boot` properly from then on.
=> fix: Use v1.0.489 tag in version stream

env/templates/arcalos-cleanup-cj.yaml, env/templates/arcalos-version-stream-update-cj.yaml, env/templates/e2e-gc-cj.yaml, env/templates/jx-issue-lifecycle-close-cj.yaml, env/templates/jx-issue-lifecycle-rotten-cj.yaml, env/templates/jx-issue-lifecycle-stale-cj.yaml, env/templates/sync-nginx-images-cj.yaml, env/templates/version-stream-update-cj.yaml
Everything but `copy-charts-index` is moving now, that'll follow when we actually move builds over etc.
See https://github.com/jenkins-x/environment-oss-weasel-dev/pull/4 for the new cronjobs.
=> chore: Disable cronjobs moving to oss-weasel

repositories/templates/lh-group.yaml
Doing a trial run of an individual project first.
=> chore: Move jenkins-x/lighthouse repository to oss-weasel

env/templates/copy-charts-index-cj.yaml
It works on oss-weasel now, so...
=> chore: Disable the copy-chart-index cronjob
